[package]
name = "cloud_thingy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
names = "0.13.0"
rand = "0.8.5"
